presentation/Store.Web/Models/ErrorViewModel.cs
using System;

namespace Store.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

presentation/Store.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;
using System.Threading.Tasks;

namespace Store.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly BookService bookService;

        public BookController(BookService bookService)
        {
            this.bookService = bookService;
        }

        public async Task<IActionResult> Index(int id)
        {
            var model = await bookService.GetByIdAsync(id);
            
            return View(model);
        }
    }
}

presentation/Store.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Store.Web.Models;

namespace Store.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

presentation/Store.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Store.Contractors;
using Store.Web.App;
using Store.Web.Contractors;

namespace Store.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderService orderService;
        private readonly IEnumerable<IDeliveryService> deliveryServices;
        private readonly IEnumerable<IPaymentService> paymentServices;
        private readonly IEnumerable<IWebContractorService> webContractorServices;

        public OrderController(OrderService orderService,
                               IEnumerable<IDeliveryService> deliveryServices,
                               IEnumerable<IPaymentService> paymentServices,
                               IEnumerable<IWebContractorService> webContractorServices)
        {
            this.orderService = orderService;
            this.deliveryServices = deliveryServices;
            this.paymentServices = paymentServices;
            this.webContractorServices = webContractorServices;
        }

        //[HttpGet]
        //public IActionResult Index()
        //{
        //    if (orderService.TryGetModel(out OrderModel model))
        //        return View(model);

        //    return View("Empty");
        //}

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var (hasValue, model) = await orderService.TryGetModelAsync();
            if (hasValue)
                return View(model);

            return View("Empty");
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(int bookId, int count = 1)
        {
            await orderService.AddBookAsync(bookId, count);

            return RedirectToAction("Index", "Book", new { id = bookId });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateItem(int bookId, int count)
        {
            var model = await orderService.UpdateBookAsync(bookId, count);

            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItem(int bookId)
        {
            var model = await orderService.RemoveBookAsync(bookId);

            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> SendConfirmation(string cellPhone)
        {
            var model = await orderService.SendConfirmationAsync(cellPhone);

            return View("Confirmation", model);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmCellPhone(string cellPhone, int confirmationCode)
        {
            var model = await orderService.ConfirmCellPhoneAsync(cellPhone, confirmationCode);

            if (model.Errors.Count > 0)
                return View("Confirmation", model);

            var deliveryMethods = deliveryServices.ToDictionary(service => service.Name,
                                                                service => service.Title);

            return View("DeliveryMethod", deliveryMethods);
        }

        [HttpPost]
        public async Task<IActionResult> StartDelivery(string serviceName)
        {
            var deliveryService = deliveryServices.Single(service => service.Name == serviceName);
            var order = await orderService.GetOrderAsync();
            var form = deliveryService.FirstForm(order);

            var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
            if (webContractorService == null)
                return View("DeliveryStep", form);

            var returnUri = GetReturnUri(nameof(NextDelivery));
            var redirectUri = await webContractorService.StartSessionAsync(form.Parameters, returnUri);

            return Redirect(redirectUri.ToString());
        }

        private Uri GetReturnUri(string action)
        {
            var builder = new UriBuilder(Request.Scheme, Request.Host.Host)
            {
                Path = Url.Action(action),
                Query = null,
            };

            if (Request.Host.Port != null)
                builder.Port = Request.Host.Port.Value;

            return builder.Uri;
        }

        [HttpPost]
        public async Task<IActionResult> NextDelivery(string serviceName, int step, Dictionary<string, string> values)
        {
            var deliveryService = deliveryServices.Single(service => service.Name == serviceName);

            var form = deliveryService.NextForm(step, values);
            if (!form.IsFinal)
                return View("DeliveryStep", form);

            var delivery = deliveryService.GetDelivery(form);
            await orderService.SetDeliveryAsync(delivery);

            var paymentMethods = paymentServices.ToDictionary(service => service.Name,
                                                              service => service.Title);

            return View("PaymentMethod", paymentMethods);
        }

        [HttpPost]
        public async Task<IActionResult> StartPayment(string serviceName)
        {
            var paymentService = paymentServices.Single(service => service.Name == serviceName);
            var order = await orderService.GetOrderAsync();
            var form = paymentService.FirstForm(order);

            var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
            if (webContractorService == null)
                return View("PaymentStep", form);

            var returnUri = GetReturnUri(nameof(NextPayment));
            var redirectUri = await webContractorService.StartSessionAsync(form.Parameters, returnUri);

            return Redirect(redirectUri.ToString());
        }

        [HttpPost]
        public async Task<IActionResult> NextPayment(string serviceName, int step, Dictionary<string, string> values)
        {
            var paymentService = paymentServices.Single(service => service.Name == serviceName);

            var form = paymentService.NextForm(step, values);
            if (!form.IsFinal)
                return View("PaymentStep", form);

            var payment = paymentService.GetPayment(form);
            var model = await orderService.SetPaymentAsync(payment);

            return View("Finish", model);
        }
    }
}

presentation/Store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;
using System.Threading.Tasks;

namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly BookService bookService;

        public SearchController(BookService bookService)
        {
            this.bookService = bookService;
        }

        public async Task<IActionResult> Index(string query)
        {
            var books = await bookService.GetAllByQueryAsync(query);

            return View("Index", books);
        }
    }
}

presentation/Store.Web/Views/Book/Index.cshtml
@model BookModel

@{
    ViewData["Title"] = Model.Title;
}

<h1>@Model.Title</h1>
<p><strong>@Model.Author</strong></p>
<p>@Model.Description</p>
<p>Цена <strong>@Model.Price</strong></p>
<form action="@Url.Action(nameof(OrderController.AddItem), "Order")" method="post">
    <input type="hidden" name="bookId" value="@Model.Id" />
    <button class="btn btn-success" type="submit">В корзину</button>
</form>

presentation/Store.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Интернет-магазин на C#";
}

<p>
    Если вы молодой программист и у вас не очень много опыта, некоторые темы в современном программировании могут показаться вам слишком абстрактными.
</p>
<p>
    Например, такие, как паттерны проектирования или принципы SOLID.
    Когда меня спрашивают про SOLID, я понимаю, что все короткие ответы меня не удовлетворяют. В то же время, работая в команде, я могу рассказывать младшим программистам об абстракциях на примере нашего собственного кода. Такие рассказы гораздо доходчивее.
</p>
<p>
    Промышленная разработка — лучшая ситуация для обучения, если вам повезло с проектом, командой и тим-лидом. Но что делать, если не повезло?
</p>
<p>
    В московском клубе программистов регулярно делают доклады на тему паттернов, DDD, SOLID. К сожалению, они носят слишком обзорный характер.о-первых, продолжительность доклада всего сорок минут; а во-вторых, этот формат не позволяет раскрывать детали.
</p>
<p>
    Нужен совместный проект, в котором можно столкнуться реальными проблемами и решать их, попутно осваивая теорию. Проект должен быть достаточно условным и учебным, чтобы за деревьями мы не потеряли лес — наша задача не в запуске программы, а в том, чтобы научиться.
</p>

<h3>Проект</h3>
<p>
    В качестве учебного проекта мы возьмём книжный интернет-магазин. Каждый из нас покупал книги в интернете и хорошо представляет предметную область. Нам не придётся пару недель разбираться в том, что мы хотим сделать.
</p>
<p>
    С другой стороны, интернет-магазин уже достаточно велик и практичен, чтобы мы могли столкнуться с проблемами и понять, как абстрактные знания помогают их решать.
</p>

<h2>Формат</h2>
<p>
    Место обучения: Zoom
</p>
<p>
    Длительность занятия: 1,5 часа
</p>
<p>
    Расписание занятий: каждый вторник с 19:00 до 20:30, начиная с 28 апреля (28.04, 05.05, 12.05, 19.05, 26.05, 02.06, 09.06, 16.06).
</p>
<p>
    Продолжительность: 8 встреч, то есть полный курс займёт два месяца.
</p>
<p>
    По согласованию с участниками, количество встреч может быть изменено.
</p>
<p>
    Курс бесплатный и это накладывает ограничение на участников. Вам должно быть интересно учиться. И вы должны помогать друг другу.
</p>
<p>
    Что конкретно будет происходить:
</p>
<ol>
    <li>Мы будем обсуждать задачи и их решения.</li>
    <li>Мы будем обсуждать задачи и их решения.</li>
    <li>Я буду расшаривать экран и писать код, попутно объясняя, что и зачем я делаю.</li>
    <li>Я буду отвечать на вопросы.</li>
    <li>Весь урок будет записан и выложен в YouTube, так что вы сможете позже просмотреть его и поэкспериментировать с кодом самостоятельно.</li>
</ol>

<h3>Темы</h3>
<ul>
    <li>C#</li>
    <li>SQL</li>
    <li>git и GitHub</li>
    <li>Agile: бэклог, пользовательские истории, итерации</li>
    <li>Модульное тестирование</li>
    <li>Паттерны проектирования</li>
    <li>Принципы SOLID</li>
    <li>DDD (Domain Driven Design)</li>
    <li>ASP.NET MVC</li>
    <li>Entity Framework</li>
</ul>
<p>
    У нас интернет-магазин, поэтому, конечно, нам придётся использовать HTML, CSS и JavaScript. Я не планирую глубоко погружаться в эти темы, в том числе потому, что не специализируюсь на них и глубоко не разбираюсь.
</p>

<h3>Пожелания</h3>
<p>
    Не всем этот курс может быть полезен. Если вы хотите научиться программировать с нуля, этот курс окажется слишком сложным. Если вы старший программист, то вряд ли узнаете что-то новое.
</p>
<p>
    Курс подойдёт вам, если вы программируете несколько лет и знаете два-три языка программирования. Хорошо, если один из этих языков является наследником C, то есть это C , C#, Java, PHP, JavaScript.
    Важно, чтобы вы понимали основы объектно-ориентированного программирования, чтобы вас не пугали термины класс, объект и наследование.
</p>
<p>
    Разработка будет вестись в Visual Studio 2019 Community Edition. Это бесплатная IDE от Microsoft, которая работает под Windows. Её можно запустить на MacOS. Разрабатывать код можно будет и под Linux в вашем любимом редакторе. У меня нет опыта в разработке под MacOS и Linux, поэтому, если что-то не пойдёт не так, я возможно не смогу вам помочь.
</p>
<p>
    <a href="https://www.youtube.com/watch?v=L2OC525fkGk&list=PLfkikHwnACaXxUu9YGnQQp7VEYcMmuBuq">Видео-записи занятий</a>.
</p>

presentation/Store.Web/Views/Order/Confirmation.cshtml
@model OrderModel

@{
    ViewData["Title"] = "Подтверждение мобильного";
}

<h1>Подтверждение мобильного</h1>

<p>
    Введите <em>код подтверждения</em> из SMS.
</p>

<form action="@Url.Action(nameof(OrderController.ConfirmCellPhone))" method="post">
    <input type="hidden" name="cellPhone" value="@Model.CellPhone" />
    <div class="form-group">
        <label for="confirmationCode">Код потдверждения</label>
        <input type="text" class="form-control" name="confirmationCode" placeholder="0000" />
        @if (Model.Errors.ContainsKey("confirmationCode"))
        {
            <small class="form-text text-danger">@Model.Errors["confirmationCode"]</small>
        }
    </div>
    <button type="submit" class="btn btn-success">Проверить</button>
</form>

<p>
    Если на ваш номер SMS не пришла в течение минуты, проверьте правильность номера и
    повторите отправку кода.
</p>

<form action="@Url.Action("SendConfirmationCode")" method="post">
    <div class="form-group">
        <label for="cellPhone">Мобильный телефон</label>
        <input type="text" class="form-control" name="cellPhone" value="@Model.CellPhone" />
        @if (Model.Errors.ContainsKey("cellPhone"))
        {
            <small class="form-text text-danger">@Model.Errors["cellPhone"]</small>
        }
    </div>
    <button type="submit" class="btn btn-success">Повторить код</button>
</form>

presentation/Store.Web/Views/Order/DeliveryMethod.cshtml
@model IReadOnlyDictionary<string, string>
@{
    ViewData["Title"] = "Способ доставки";
}

<h1>Способ доставки</h1>

<form action="@Url.Action(nameof(OrderController.StartDelivery))" method="post">
    <div class="form-group">
        <label for="code">Способ доставки:</label>
        <select class="form-control" name="serviceName">
            @foreach (var method in Model)
            {
                <option value="@method.Key">@method.Value</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-success">Далее</button>
</form>


presentation/Store.Web/Views/Order/DeliveryStep.cshtml
@using Store.Web.Controllers
@model Form

@{
    ViewData["Title"] = "Параметры доставки";
}

<h1>Параметры доставки</h1>
<form action="@Url.Action(nameof(OrderController.NextDelivery))" method="post">
    <input type="hidden" name="serviceName" value="@Model.ServiceName" />
    <input type="hidden" name="step" value="@Model.Step" />
    @foreach (var parameter in Model.Parameters)
    {
        <input type="hidden" name="values[@parameter.Key]" value="@parameter.Value" />
    }
    @foreach (var field in Model.Fields)
    {
        if (field is SelectionField selectionField)
        {
            <div class="form-group">
                <label for="values[@field.Name]">@field.Label</label>
                <select class="form-control" name="values[@field.Name]">
                @foreach (var item in selectionField.Items)
                {
                    <option value="@item.Key">@item.Value</option>
                }
                </select>
            </div>
        }
    }
    <button type="submit" class="btn btn-success">Далее</button>
</form>

presentation/Store.Web/Views/Order/Empty.cshtml

@{
    ViewData["Title"] = "Корзина пуста";
}

<h1>Корзина пуста</h1>


presentation/Store.Web/Views/Order/Finish.cshtml
@model OrderModel
@{
    ViewData["Title"] = "Заказ оформлен";
}

<p>
    Заказ оформлен. Мы собираем его, чтобы передать в службу доставки.
    Ждите SMS.
</p>

<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Автор</th>
            <th scope="col">Название</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Items.Length; i++)
        {
            <tr>
                <td class="text-right">@(i + 1)</td>
                <td>@Model.Items[i].Author</td>
                <td>@Model.Items[i].Title</td>
                <td class="text-right">@Model.Items[i].Count</td>
                <td class="text-right">@Model.Items[i].Price</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого</td>
            <td class="text-right">@Model.TotalCount</td>
            <td class="text-right">@Model.TotalPrice</td>
        </tr>
    </tfoot>
</table>

<strong>Доставка</strong>
<pre>
@Model.DeliveryDescription
</pre>

<strong>Оплата</strong>
<pre>
@Model.PaymentDescription
</pre>

<p>
    <a href="@Url.Action("Index", "Home")">Вернутся в магазин</a>.
</p>

presentation/Store.Web/Views/Order/Index.cshtml
@model OrderModel

@{
    ViewData["Title"] = "Корзина";
}

<h1>Корзина</h1>

<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Автор</th>
            <th scope="col">Название</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Items.Length; i++)
        {
            <tr>
                <td class="text-right">@(i + 1)</td>
                <td>@Model.Items[i].Author</td>
                <td>@Model.Items[i].Title</td>
                <td class="text-right">@Model.Items[i].Count</td>
                <td class="text-right">@Model.Items[i].Price</td>
                <td class="text-center">
                    <form class="form-inline" action="@Url.Action("RemoveItem", "Order")" method="post">
                        <input type="hidden" name="bookId" value="@Model.Items[i].BookId" />
                        <button class="btn btn-danger" type="submit">Удалить</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого</td>
            <td class="text-right">@Model.TotalCount</td>
            <td class="text-right">@Model.TotalPrice</td>
        </tr>
    </tfoot>
</table>

<p>
    Для оформления заказа необходимо подтвердить номер вашего мобильного.
    Введите номер и нажмите <em>Отправить код</em>. На ваш номер будет отправлен *код подтверждения*.
</p>

<form action="@Url.Action(nameof(OrderController.SendConfirmation))" method="post">
    <div class="form-group">
        <label for="cellPhone">Мобильный телефон</label>
        <input type="text" class="form-control" name="cellPhone" placeholder="+79876543210" value="+79876543210" />
        @if (Model.Errors.ContainsKey("cellPhone"))
        {
            <small class="form-text text-danger">@Model.Errors["cellPhone"]</small>
        }
    </div>
    <button type="submit" class="btn btn-success">Отправить код</button>
</form>

presentation/Store.Web/Views/Order/PaymentMethod.cshtml
@model IReadOnlyDictionary<string, string>
@{
    ViewData["Title"] = "Способ оплаты";
}

<h1>Способ оплаты</h1>

<form action="@Url.Action(nameof(OrderController.StartPayment))" method="post">
    <div class="form-group">
        <label for="code">Способ оплаты:</label>
        <select class="form-control" name="serviceName">
        @foreach (var method in Model)
        {
            <option value="@method.Key">@method.Value</option>
        }
        </select>
    </div>
    <button type="submit" class="btn btn-success">Далее</button>
</form>


presentation/Store.Web/Views/Order/PaymentStep.cshtml
@using Store.Web.Controllers
@model Form

@{
    ViewData["Title"] = "Параметры оплаты";
}

<h1>Параметры оплаты</h1>
<form action="@Url.Action(nameof(OrderController.NextPayment))" method="post">
    <input type="hidden" name="serviceName" value="@Model.ServiceName" />
    <input type="hidden" name="step" value="@Model.Step" />
    @foreach (var parameter in Model.Parameters)
    {
        <input type="hidden" name="values[@parameter.Key]" value="@parameter.Value" />
    }
    @foreach (var field in Model.Fields)
    {
        if (field is SelectionField selectionField)
        {
            <div class="form-group">
                <label for="values[@field.Name]">@field.Label</label>
                <select class="form-control" name="values[@field.Name]">
                @foreach (var item in selectionField.Items)
                {
                    <option value="@item.Key">@item.Value</option>
                }
                </select>
            </div>
        }
    }
    <button type="submit" class="btn btn-success">Далее</button>
</form>

presentation/Store.Web/Views/Search/Index.cshtml
@model IReadOnlyCollection<BookModel>

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if (Model.Count == 0)
{
    <p>Ничего не найдено.</p>
}
else
{
    <ul>
    @foreach (var book in Model)
    {
        <li><a href="@Url.Action("Index", "Book", new { id = book.Id })">@book.Title</a></li>
    }
    </ul>
}

presentation/Store.Web/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Страница не найдена";
}

<h1 class="text-danger">Страница не найдена</h1>

presentation/Store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - интернет-магазин на C#</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Интернет-магазин на C#</a>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("Index", "Search")" method="get">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="автор или название" />
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Искать</button>
            </form>
            <span class="navbar-text ml-auto">
             @{
                 if (Context.Session.TryGetCart(out Cart cart) && cart.TotalCount > 0)
                 {
                     <a href="@Url.Action("Index", "Order")">Товаров @cart.TotalCount на сумму @cart.TotalPrice</a>
                 }
                 else
                 {
                     @:Корзина пуста
                 }
             }
            </span>
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>